name: base
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - anaconda-anon-usage=0.5.0
  - anaconda_powershell_prompt=1.1.0
  - anaconda_prompt=1.1.0
  - annotated-types=0.6.0
  - archspec=0.2.3
  - boltons=24.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - conda=25.1.1
  - conda-anaconda-telemetry=0.1.2
  - conda-anaconda-tos=0.1.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.1.1
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - cpp-expected=1.1.0
  - cryptography=43.0.3
  - distro=1.9.0
  - fmt=9.1.0
  - frozendict=2.4.2
  - idna=3.7
  - jsonpatch=1.33
  - jsonpointer=2.1
  - libarchive=3.7.7
  - libcurl=8.11.1
  - libffi=3.4.4
  - libiconv=1.16
  - libmamba=2.0.5
  - libmambapy=2.0.5
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - mdurl=0.1.0
  - menuinst=2.2.0
  - nlohmann_json=3.11.2
  - openssl=3.0.15
  - packaging=24.2
  - pcre2=10.42
  - pip=25.0
  - platformdirs=3.10.0
  - pluggy=1.5.0
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.10.16
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - rich=13.9.4
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - setuptools=75.8.0
  - simdjson=3.10.1
  - spdlog=1.11.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tqdm=4.67.1
  - truststore=0.10.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - albucore==0.0.24
      - albumentations==2.0.8
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - astunparse==1.6.3
      - audioread==3.0.1
      - beautifulsoup4==4.13.4
      - blinker==1.9.0
      - click==8.2.1
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - crcmod==1.7
      - cycler==0.12.1
      - cython==3.1.2
      - decorator==5.2.1
      - deepface==0.0.93
      - easydict==1.13
      - editdistance==0.8.1
      - exceptiongroup==1.3.0
      - facenet-pytorch==2.5.0
      - faiss-cpu==1.11.0
      - fastapi==0.115.13
      - ffmpeg==1.4
      - ffmpeg-python==0.2.0
      - filelock==3.18.0
      - fire==0.7.0
      - flask==3.1.1
      - flask-cors==6.0.1
      - flatbuffers==25.2.10
      - fonttools==4.58.4
      - fsspec==2025.5.1
      - funasr==1.2.6
      - future==1.0.0
      - gast==0.6.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-pasta==0.2.0
      - grpcio==1.73.1
      - gunicorn==23.0.0
      - h11==0.16.0
      - h5py==3.14.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.33.1
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - imageio==2.37.0
      - insightface==0.7.3
      - itsdangerous==2.2.0
      - jaconv==0.4.0
      - jamo==0.4.1
      - jieba==0.42.1
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.5.1
      - kaldiio==2.18.1
      - keras==3.10.0
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - libclang==18.1.1
      - librosa==0.11.0
      - llvmlite==0.44.0
      - lz4==4.4.4
      - markdown==3.8.2
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - ml-dtypes==0.5.1
      - modelscope==1.27.1
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - mtcnn==1.0.0
      - namex==0.1.0
      - networkx==3.4.2
      - nudenet==3.4.2
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.10.2.21
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - omegaconf==2.3.0
      - onnx==1.18.0
      - onnxruntime==1.16.0
      - onnxruntime-gpu==1.16.0
      - openai-whisper==20250625
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.3.0
      - optree==0.16.0
      - oss2==2.19.1
      - paddlepaddle-gpu==3.1.0
      - pandas==2.3.0
      - pillow==11.2.1
      - pooch==1.8.2
      - prettytable==3.16.0
      - protobuf==5.29.5
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyclipper==1.3.0.post6
      - pycryptodome==3.23.0
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytorch-wpe==0.0.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - rapidocr-paddle==1.4.5
      - regex==2024.11.6
      - retina-face==0.0.17
      - scikit-image==0.25.2
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - shapely==2.1.1
      - simsimd==6.4.9
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.7
      - soxr==0.5.0.post1
      - starlette==0.46.2
      - stringzilla==3.12.5
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - tf-keras==2.19.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tiktoken==0.9.0
      - torch==2.1.0+cu118
      - torch-complex==0.4.4
      - torchaudio==2.1.0+cu118
      - torchvision==0.16.0+cu118
      - tzdata==2025.2
      - ultralytics==8.3.156
      - ultralytics-thop==2.0.14
      - umap-learn==0.5.7
      - uvicorn==0.34.3
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - wrapt==1.17.2

